.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH PYQONSOLE 1 "February 15, 2006"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
pyqonsole \- VT102 emulator written in Python and PyQt3
.SH SYNOPSIS
.B pyqonsole
.RI [ executable ] 
.br
.SH DESCRIPTION
.B pyqonsole 
is a VT-102 emulator which can be used as a replacement for
an X terminal emulator, though it will be slower and use more memory than a
traditional X terminal emulator. Its main purpose is to provide a
VT-102 emulator widget for Python programmers. 

By default, it will launch the current user's shell (based on
/etc/passwd) or bash, if no information is available in
/etc/passwd. An executable name can be specified on the command line,
in which case, it will be run in the emulator. 

.PP
.SH OPTIONS
.B pyqonsole
accepts a few options, mainly for development and debugging
purposes. Use -h to see them. 

.SH AUTHOR
.B pyqonsole 
was written by Sylvain Thenault
<sylvain.thenault@logilab.fr>, based on 
.B konsole 
written by Lars Doelle <lars.doelle@on-line.de>.
.PP
This manual page was written by Alexandre Fayolle <afayolle@debian.org>,
for the Debian project (but may be used by others).
