.TH pyqonsole 1 "2006-1-3" pyqonsole
.SH NAME
.B pyqonsole
\- terminal coded in python using the Qt widget set

.SH SYNOPSIS
.B  pyqonsole
[
.I OPTIONS
] [
.I <arguments>
]

.SH DESCRIPTION
.B pyqonsole
is a terminal emulator written in Python using the Qt widget set.

.SH OPTIONS
.IP "--help, -h"
show help message and exit
.IP "--profile"
show profiling information

.SH SEE ALSO
/usr/share/doc/pyqonsole/

.SH LICENSE
This program is free software; you can redistribute it and/or modify it under
the terms of the CECILL license, available at
http://www.inria.fr/valorisation/logiciels/Licence.CeCILL-V1.pdf

Please refer to source code for precise copyrights.

.SH AUTHOR
Nicolas Chauvat <nicolas.chauvat@logilab.fr>

